### ISSUE TITLE
作者你好，偶然发现宝地，但是不清楚如何使用，不知可有具体的例子？

### ISSUE THREAD

**Issue by fusang1337** [sheng007/10086-IPTV#2]

**Comment by sheng007** [comment]
主要是：10086-iTV-EPG.xml.gz
你可以通过：
https://raw.githubusercontent.com/sheng007/10086-IPTV/master/10086-iTV-EPG.xml.gz
在IPTV软件里面引用他，例如：PerfectPlayer， IPTV Pro， KODI等


m3u一个例子：

#EXTINF:-1, tvg-name="广东卫视" tvg-logo="https://raw.githubusercontent.com/sheng007/10086-IPTV/master/up_tv_ico/%E5%B9%BF%E4%B8%9C%E5%8D%AB%E8%A7%86.png", 广东卫视
http://168.168.0.88:8888/rtp/239.10.0.141:1025

**Comment by sheng007** [comment]
貌似“raw.githubusercontent.com”已经被嗝屁了，可能是个案吧

**Comment by fusang1337** [comment]
十分感谢 我抓取了我们当地移动的源 需要请自取。ip需要换成你们当地的。
